DROP TABLE IF EXISTS userinput;

CREATE TABLE userinput (
    id INTEGER PRIMARY KEY AUTOINCREMENT,
    fname TEXT NOT NULL,
    modele TEXT NOT NULL,
    problem TEXT NOT NULL,
    created TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP
);